name: CI
on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get blame
        run: git blame --line-porcelain -L 1,6 newFile.txt
      - name: Blame Alert
        uses: molleer/blame-alert@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
